### ISSUE TITLE
bug: `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by jcstein** [rollkit/rollkit#1059]
Observed testing out docs in https://github.com/rollkit/docs/pull/186

Full logs of rollkit node: https://app.warp.dev/block/Umjjh5DfFI44GGN3WoTgYJ

Logs from light node: https://app.warp.dev/block/nbsQ7lYKCWIisGm9t5PUaB

```bash
2:11PM INF indexed block height=4 module=txindex
2:11PM INF successfully submitted Rollkit block to DA layer daHeight=42606 module=BlockManager rollkitHeight=4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100f1da58]

goroutine 233 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0x14001494380)
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:310 +0x88
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0x140011faa80)
	github.com/tendermint/tendermint@v0.35.9/abci/client/local_client.go:297 +0xe0
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x140006dc0a0?)
	github.com/tendermint/tendermint@v0.35.9/proxy/app_conn.go:96 +0x28
github.com/rollkit/rollkit/state.(*BlockExecutor).commit(_, {_, _}, {{{0xb, 0x0}, {0x101c04947, 0x7}}, {0x14001473730, 0x9}, 0x1, ...}, ...)
	github.com/rollkit/rollkit@v0.9.0/state/executor.go:271 +0xc4
github.com/rollkit/rollkit/state.(*BlockExecutor).Commit(_, {_, _}, {{{0xb, 0x0}, {0x101c04947, 0x7}}, {0x14001473730, 0x9}, 0x1, ...}, ...)
	github.com/rollkit/rollkit@v0.9.0/state/executor.go:179 +0x64
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0x14000128000, {0x102c4bc70, 0x140012478b0})
	github.com/rollkit/rollkit@v0.9.0/block/manager.go:586 +0x730
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0x14000128000, {0x102c4bc70, 0x140012478b0}, 0x0)
	github.com/rollkit/rollkit@v0.9.0/block/manager.go:212 +0x1d8
created by github.com/rollkit/rollkit/node.(*FullNode).OnStart
	github.com/rollkit/rollkit@v0.9.0/node/full.go:312 +0x56c
```

**Comment by nodebreaker0-0** [comment]
I'm suffering from the same bug, it only throws an error under very specific conditions, and it's asynchronous.
version : cosmos-sdk@v0.45.16

Most likely tendermint@v0.35.9 is customizing the syntax incorrectly.

**Comment by Manav-Aggarwal** [comment]
Is this still an issue? @nodebreaker0-0 we removed the cometbft (previously tendermint) dependency, and have new rollkit version (v10.2) and corresponding docs.

**Comment by Manav-Aggarwal** [comment]
Closing this stale issue, please re-open if it persists.
