### ISSUE TITLE
nil pointer derefrence on invalid RPC request

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#1149]
### Version of Git SHA

v0.10.1

### System OS

MacOS, Intel

### Installed tools

github.com/rollkit/cosmos-sdk v0.47.3-rollkit-v0.10.1-no-fraud-proofs

### Steps to reproduce it

`curl http://localhost:26657/block`

### Expected result

the exception should be caught

### Actual result

expected result is correct, but the node logs a seemingly uncaught nil pointer exception

### Relevant log output

```Shell
2023/08/18 14:38:01 http: panic serving 127.0.0.1:57783: runtime error: invalid memory address or nil pointer dereference
goroutine 513 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x102408ca0, 0x104ff4050})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/gorilla/rpc/v2/json2.(*CodecRequest).WriteError(0xc0011b0f60, {0x103819ef0, 0xc00255a000}, 0x6?, {0x0?, 0x0?})
	/Users/colludingnode/go/pkg/mod/github.com/gorilla/rpc@v1.2.0/v2/json2/server.go:193 +0xb1
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0xc000ef52f0, {0x103819ef0, 0xc00255a000}, 0xc006f20a00, 0x0)
	/Users/colludingnode/go/pkg/mod/github.com/rollkit/rollkit@v0.10.1/rpc/json/handler.go:72 +0x6a9
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/colludingnode/go/pkg/mod/github.com/rollkit/rollkit@v0.10.1/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x0?, {0x103819ef0?, 0xc00255a000?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00266fad8?, {0x103819ef0, 0xc00255a000}, 0xc006f20a00)
	/usr/local/go/src/net/http/server.go:2500 +0x149
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x0?, {0x103819ef0?, 0xc00255a000?}, 0x100592b74?)
	/Users/colludingnode/go/pkg/mod/github.com/rollkit/rollkit@v0.10.1/rpc/json/handler.go:47 +0x27
net/http.serverHandler.ServeHTTP({0x103801250?}, {0x103819ef0, 0xc00255a000}, 0xc006f20a00)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc005224240, {0x10381d948, 0xc0011c0e70})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed

```
```


### Notes

_No response_

**Comment by nashqueue** [comment]
Can you reproduce it with 10.2?

**Comment by chandiniv1** [comment]
@nashqueue ,I'm also getting same log output 
![image (1)](https://github.com/rollkit/rollkit/assets/117723967/66321a96-663f-4de4-8f86-f3d191087462)
 while I'm trying to set up hermes relayer between two rollup chains
hermes version: 1.6.0
![image](https://github.com/rollkit/rollkit/assets/117723967/ad6d833f-0de5-4e16-b904-a046358def69)
can you please explain how to resolve this error

**Comment by gupadhyaya** [comment]
tested using rollkit v0.11.9 and seems to be working fine.
`curl http://localhost:26657/block`
```
{"jsonrpc":"2.0","id":-1,"result":{"block_id":{"hash":"1239BC1EE2EB446ED965CDEA2A6D155BB6AC41BAE66A6A6197A2E5A890A34CFB","parts":{"total":1,"hash":"78A275F264205D62675D05A7FE1574CB9EA870AFAF0AE5B6BF1AAEBCE7B2CBE9"}},"block":{"header":{"version":{"block":"11","app":"1"},"chain_id":"test","height":"3549","time":"2024-01-16T10:09:11.15924617Z","last_block_id":{"hash":"25E6E1AC8367198D34238E4EA06B6B95163E82C5F21C5E4410E358E5E7D6DE06","parts":{"total":1,"hash":"CD5C3FCB865C4672D0605A8DD170655B84B7140F9FE8A22737575D8661608E9B"}},"last_commit_hash":"8E6E00CCE1735493ED6CDF9B0A4B4A809EDFB26E6EECE559558F57C409EFFDC0","data_hash":"3D96B7D238E7E0456F6AF8E7CDF0A67BD6CF9C2089ECB559C659DCAA1F880353","validators_hash":"5BC1CBA2DA2B1D3C104D6E1A146D3050FFA6FD77CD4C25F349F8437499933290","next_validators_hash":"5BC1CBA2DA2B1D3C104D6E1A146D3050FFA6FD77CD4C25F349F8437499933290","consensus_hash":"C0B6A634B72AE9687EA53B6D277A73ABA1386BA3CFC6D0F26963602F7F6FFCD6","app_hash":"51FE557C66D01C0BA1C2D00DB684DFF96952D9364B05D9F82E48B560EB70317D","last_results_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","evidence_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","proposer_address":"489540A144482B7AAF96BCA67E10E27F4A07C501"},"data":{"txs":[],"square_size":"1"},"evidence":{"evidence":[]},"last_commit":{"height":"3548","round":0,"block_id":{"hash":"25E6E1AC8367198D34238E4EA06B6B95163E82C5F21C5E4410E358E5E7D6DE06","parts":{"total":1,"hash":"CD5C3FCB865C4672D0605A8DD170655B84B7140F9FE8A22737575D8661608E9B"}},"signatures":[{"block_id_flag":2,"validator_address":"489540A144482B7AAF96BCA67E10E27F4A07C501","timestamp":"2024-01-16T10:09:11.15924617Z","signature":"tHBuHqugvo22mSkmZNDudSdQKaPSgWiQcYiTyiXvQKdc2aDYzqAQj7fEr+rDABSI5dkX+vnFxJRnV1mpiGXMCg=="}]}}}}
```
