### ISSUE TITLE
Test Failure

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1339]
https://github.com/rollkit/rollkit/actions/runs/6866494981/job/18672848892
```
    ws_test.go:63: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:63
        	Error:      	Received unexpected error:
        	            	read tcp 127.0.0.1:45224->127.0.0.1:36881: i/o timeout
        	Test:       	TestWebSockets
    ws_test.go:64: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:64
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : -1
        	Test:       	TestWebSockets
    ws_test.go:65: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:65
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestWebSockets
    ws_test.go:68: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:68
        	Error:      	Received unexpected error:
        	            	unexpected end of JSON input
        	Test:       	TestWebSockets
    ws_test.go:70: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:70
        	Error:      	Expected value not to be nil.
        	Test:       	TestWebSockets
--- FAIL: TestWebSockets (3.04s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20161b8]

goroutine 1198 [running]:
testing.tRunner.func1.2({0x21b8e00, 0x3696630})
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1526 +0x372
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1529 +0x650
panic({0x21b8e00, 0x3696630})
	/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/panic.go:890 +0x263
github.com/rollkit/rollkit/rpc/json.TestWebSockets(0xc01c526ea0)
	/home/runner/work/rollkit/rollkit/rpc/json/ws_test.go:71 +0x718
testing.tRunner(0xc01c526ea0, 0x26b84c0)
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1629 +0x806
FAIL	github.com/rollkit/rollkit/rpc/json	3.347s
```

**Comment by MSevey** [comment]
this failure appears to be from the test taking longer than the 1s added as the time out to execute. resolving for now. if this is more than a 1 off we can re-open and extend the timeout.
