### ISSUE TITLE
Test Failure on main

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1410]
```
=== RUN   TestUnconfirmedTxs
=== RUN   TestUnconfirmedTxs/no_txs
I[2023-12-11|16:54:06.455] service start                                module=proxy msg="Starting multiAppConn service" impl=multiAppConn
I[2023-12-11|16:54:06.455] service start                                module=abci-client connection=query msg="Starting localClient service" impl=localClient
I[2023-12-11|16:54:06.455] service start                                module=abci-client connection=snapshot msg="Starting localClient service" impl=localClient
I[2023-12-11|16:54:06.455] service start                                module=abci-client connection=mempool msg="Starting localClient service" impl=localClient
I[2023-12-11|16:54:06.455] service start                                module=abci-client connection=consensus msg="Starting localClient service" impl=localClient
I[2023-12-11|16:54:06.455] service start                                module=events msg="Starting EventBus service" impl=EventBus
I[2023-12-11|16:54:06.455] service start                                module=pubsub msg="Starting PubSub service" impl=PubSub
I[2023-12-11|16:54:06.455] WARNING: working in in-memory mode           
panic: write /tmp/TestTx.log1587061537: file already closed

goroutine 2023 [running]:
github.com/rollkit/rollkit/test/log.(*FileLogger).Info(0xc0217ddcb0, {0x22942e9, 0xf}, {0xc01bcc7680, 0x8, 0x1ac900d6?})
	/home/runner/work/rollkit/rollkit/test/log/loggers.go:74 +0x2fb
github.com/rollkit/rollkit/state.(*BlockExecutor).execute(_, {_, _}, {{{0xb, 0x0}, {0x222fbc6, 0xa}}, {0x2201ed4, 0x4}, 0x1, ...}, ...)
	/home/runner/work/rollkit/rollkit/state/executor.go:365 +0xe17
github.com/rollkit/rollkit/state.(*BlockExecutor).ApplyBlock(_, {_, _}, {{{0xb, 0x0}, {0x222fbc6, 0xa}}, {0x2201ed4, 0x4}, 0x1, ...}, ...)
	/home/runner/work/rollkit/rollkit/state/executor.go:213 +0x258
github.com/rollkit/rollkit/block.(*Manager).applyBlock(_, {_, _}, _)
	/home/runner/work/rollkit/rollkit/block/manager.go:836 +0x225
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0xc01b96c960, {0x2792988, 0xc0108e13b0?})
	/home/runner/work/rollkit/rollkit/block/manager.go:690 +0xbf4
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0xc01b96c960, {0x2792988, 0xc0108e13b0}, 0x0)
	/home/runner/work/rollkit/rollkit/block/manager.go:268 +0x3e6
created by github.com/rollkit/rollkit/node.(*FullNode).OnStart in goroutine 1897
	/home/runner/work/rollkit/rollkit/node/full.go:334 +0x6e5
FAIL	github.com/rollkit/rollkit/node	2.437s
```

**Comment by MSevey** [comment]
this panic isn't for the test in the log as that test doesn't log to a file.
