### ISSUE TITLE
datastore: key not found while querying the tx

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1561]
Steps to reproduce:
* Run a sequencer
* Make a tx
* Query: `polard query tx 4F046AE0D5818D68402045EE60FB35A8BC8EDFC18E8828A4B646A5DF4ECEB4F0 --type=hash`

```
polard  | 2024/02/22 23:17:35 http: panic serving ****: datastore: key not found
polard  | goroutine 535 [running]:
polard  | net/http.(*conn).serve.func1()
polard  |       net/http/server.go:1868 +0xb0
polard  | panic({0x2f3f700?, 0x6540030?})
polard  |       runtime/panic.go:920 +0x26c
polard  | github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x4002305060, {0x40014315f0, 0x20, 0x46cf3c?})
polard  |       github.com/rollkit/rollkit@v0.11.4/state/txindex/kv/kv.go:55 +0x1e4
polard  | github.com/rollkit/rollkit/node.(*FullClient).Tx(0x4002c9f548, {0x400a6b9950?, 0x400a6b9980?}, {0x40014315f0, 0x20, 0x21}, 0x1)
polard  |       github.com/rollkit/rollkit@v0.11.4/node/full_client.go:531 +0x58
polard  | github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x40011b4780?)
polard  |       github.com/rollkit/rollkit@v0.11.4/rpc/json/service.go:183 +0x5c
polard  | reflect.Value.call({0x2ed93a0?, 0x40017e0300?, 0x40016ed8b8?}, {0x34f3796, 0x4}, {0x40016eda08, 0x2, 0x44?})
polard  |       reflect/value.go:596 +0x994
polard  | reflect.Value.Call({0x2ed93a0?, 0x40017e0300?, 0x40028f99e0?}, {0x40016eda08?, 0x9?, 0x45fee70?})
polard  |       reflect/value.go:380 +0x94
polard  | github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x400116f4d0, {0x463c120, 0x400147e7e0}, 0x4002414100, 0x0)
polard  |       github.com/rollkit/rollkit@v0.11.4/rpc/json/handler.go:90 +0x300
polard  | github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
polard  |       github.com/rollkit/rollkit@v0.11.4/rpc/json/handler.go:52
polard  | net/http.HandlerFunc.ServeHTTP(0x4002650b28?, {0x463c120?, 0x400147e7e0?}, 0x7abca0?)
polard  |       net/http/server.go:2136 +0x38
polard  | net/http.(*ServeMux).ServeHTTP(0x4002650b58?, {0x463c120, 0x400147e7e0}, 0x4002414100)
polard  |       net/http/server.go:2514 +0x144
polard  | github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x463c120?, 0x400147e7e0?}, 0x400147e7e0?)
polard  |       github.com/rollkit/rollkit@v0.11.4/rpc/json/handler.go:47 +0x28
polard  | net/http.serverHandler.ServeHTTP({0x462b238?}, {0x463c120?, 0x400147e7e0?}, 0x6?)
polard  |       net/http/server.go:2938 +0xbc
polard  | net/http.(*conn).serve(0x4009d69b90, {0x464e9e0, 0x4002454180})
polard  |       net/http/server.go:2009 +0x518
polard  | created by net/http.(*Server).Serve in goroutine 194
polard  |       net/http/server.go:3086 +0x4cc
```

**Comment by gupadhyaya** [comment]
confirmed that it only happens in polaris, not gm tutorial

**Comment by gupadhyaya** [comment]
noticed `tx bank send` not working on polaris/rollkit. however i tried on polaris/main and seems to be not working as well. looks like the tx is stuck in the mempool and never makes it to the block (confirmed this by sending the same tx 2nd time and i get tx already in mempool). brief search in polaris issues and found: https://github.com/berachain/polaris/issues/1483, which reports the same problem

**Comment by yarikbratashchuk** [comment]
I don't see exactly this issue with `datastore: key not found` after
- updating to the to latest version of rollkit/cosmossdk (v0.50.7-rollkit-v0.13.6-no-fraud-proofs)
- updating rollkiit/rollkit to the latest version (v0.13.6)
- setting --rollkit.block_time 1s (default) and --rollkit.da_block_time 1s
- switching DA to local-da by setting --rollkit.da_address=http://localhost:7980

But after successful `send` command:
```
root@yarik-playground-final:~/polaris# ./build/bin/polard tx bank send $DEV0 $DEV1 10abera  --keyring-backend test --home ./.tmp/polard --chain-id polaris-2061
auth_info:
  fee:
    amount: []
    gas_limit: "200000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "10"
      denom: abera
    from_address: cosmos1eng03arwkqj5rtut5uudvhmg9jdcgpd9ah4tpt
    to_address: cosmos148ymhl3yyueykuxkhcch5lu7h36r3pfuseula6
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 8BBB45ADBB79D2873E0137F8953A6F5784FEC78EFA2D937B613EC059A2BE473E
```
Querying returns "not found":
```
root@yarik-playground-final:~/polaris# ./build/bin/polard query tx 8BBB45ADBB79D2873E0137F8953A6F5784FEC78EFA2D937B613EC059A2BE473E --type=hash --home ./.tmp/polard
Usage:
  polard query tx --type=[hash|acc_seq|signature] [hash|acc_seq|signature] [flags]

Flags:
      --grpc-addr string   the gRPC endpoint to use for this chain
      --grpc-insecure      allow gRPC over insecure channels, if not the server must use TLS
      --height int         Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help               help for tx
      --node string        <host>:<port> to CometBFT RPC interface for this chain (default "tcp://localhost:26657")
  -o, --output string      Output format (text|json) (default "text")
      --type string        The type to be used when querying tx, can be one of "hash", "acc_seq", "signature" (default "hash")

Global Flags:
      --home string         directory for config and data (default "/root/.polard")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic|disabled or '*:<level>,<key>:<level>') (default "info")
      --log_no_color        Disable colored logs
      --trace               print out full stack trace on errors

10:34AM ERR failure when running app err="error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32000 - tx (8BBB45ADBB79D2873E0137F8953A6F5784FEC78EFA2D937B613EC059A2BE473E) not found"
```
So the issue (https://github.com/berachain/polaris/issues/1483) is still present

**Comment by Manav-Aggarwal** [comment]
Closing this issue since Rollkit now has support for Omni Octane and BeaconKit EVMs. Please reopen if Polaris becomes relevant again.
