### ISSUE TITLE
[ibc] create channel throws panics, however ibc transfer works fine

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1576]
Panics are seen in the gm logs:

```
2024/02/28 09:25:19 http: panic serving 127.0.0.1:56608: datastore: key not found
goroutine 21691 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1041cda60?, 0x1064ee180?})
	/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x14001711aa0, {0x1400aa5a0f0, 0x20, 0x140133a3c00?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/state/txindex/kv/kv.go:55 +0x1e4
github.com/rollkit/rollkit/node.(*FullClient).Tx(0x140013c6378, {0x10475d588, 0x1400dbcf270}, {0x1400aa5a0f0, 0x20, 0x21}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full_client.go:546 +0x60
github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x140012ac6c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/service.go:200 +0x5c
reflect.Value.call({0x1041725e0?, 0x1400139d170?, 0x1400a32b8b8?}, {0x102e0d2e0, 0x4}, {0x1400a32ba08, 0x2, 0x45?})
	/usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1041725e0?, 0x1400139d170?, 0x1400851f680?}, {0x1400a32ba08?, 0x9?, 0x103e6c778?})
	/usr/local/go/src/reflect/value.go:380 +0x94
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x14001707da0, {0x10474aef0, 0x140023867e0}, 0x14001752600, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:93 +0x32c
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x1400a32bb28?, {0x10474aef0?, 0x140023867e0?}, 0x100ba0dd0?)
	/usr/local/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x1400a32bb58?, {0x10474aef0, 0x140023867e0}, 0x14001752600)
	/usr/local/go/src/net/http/server.go:2514 +0x144
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x10474aef0?, 0x140023867e0?}, 0x140023867e0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:47 +0x28
net/http.serverHandler.ServeHTTP({0x104735b58?}, {0x10474aef0?, 0x140023867e0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x1400a785050, {0x10475d550, 0x1400210a780})
	/usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 177
	/usr/local/go/src/net/http/server.go:3086 +0x4cc
2024/02/28 09:25:19 http: panic serving 127.0.0.1:56614: datastore: key not found
goroutine 21715 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1041cda60?, 0x1064ee180?})
	/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x14001711aa0, {0x140016747b0, 0x20, 0x1008d1eac?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/state/txindex/kv/kv.go:55 +0x1e4
github.com/rollkit/rollkit/node.(*FullClient).Tx(0x140013c6378, {0x10475d588, 0x14002b9bbd0}, {0x140016747b0, 0x20, 0x21}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full_client.go:546 +0x60
github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x140012ac6c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/service.go:200 +0x5c
reflect.Value.call({0x1041725e0?, 0x1400139d170?, 0x140025c18b8?}, {0x102e0d2e0, 0x4}, {0x140025c1a08, 0x2, 0x45?})
	/usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1041725e0?, 0x1400139d170?, 0x1400e22e200?}, {0x140025c1a08?, 0x9?, 0x103e6c778?})
	/usr/local/go/src/reflect/value.go:380 +0x94
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x14001707da0, {0x10474aef0, 0x140011be8c0}, 0x140020c0d00, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:93 +0x32c
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x140162adb28?, {0x10474aef0?, 0x140011be8c0?}, 0x100ba0dd0?)
	/usr/local/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x140162adb58?, {0x10474aef0, 0x140011be8c0}, 0x140020c0d00)
	/usr/local/go/src/net/http/server.go:2514 +0x144
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x10474aef0?, 0x140011be8c0?}, 0x140011be8c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:47 +0x28
net/http.serverHandler.ServeHTTP({0x104735b58?}, {0x10474aef0?, 0x140011be8c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x14002af8000, {0x10475d550, 0x1400210a780})
	/usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 177
	/usr/local/go/src/net/http/server.go:3086 +0x4cc
2024/02/28 09:25:19 http: panic serving 127.0.0.1:56616: datastore: key not found
goroutine 21647 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1041cda60?, 0x1064ee180?})
	/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x14001711aa0, {0x1400aa5a180, 0x20, 0x1008d1eac?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/state/txindex/kv/kv.go:55 +0x1e4
github.com/rollkit/rollkit/node.(*FullClient).Tx(0x140013c6378, {0x10475d588, 0x1400dbcf360}, {0x1400aa5a180, 0x20, 0x21}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full_client.go:546 +0x60
github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x140012ac6c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/service.go:200 +0x5c
reflect.Value.call({0x1041725e0?, 0x1400139d170?, 0x140085838b8?}, {0x102e0d2e0, 0x4}, {0x14008583a08, 0x2, 0x45?})
	/usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1041725e0?, 0x1400139d170?, 0x1400851f720?}, {0x14008583a08?, 0x9?, 0x103e6c778?})
	/usr/local/go/src/reflect/value.go:380 +0x94
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x14001707da0, {0x10474aef0, 0x140023868c0}, 0x14001752700, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:93 +0x32c
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x1400010fb28?, {0x10474aef0?, 0x140023868c0?}, 0x100ba0dd0?)
	/usr/local/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x1400010fb58?, {0x10474aef0, 0x140023868c0}, 0x14001752700)
	/usr/local/go/src/net/http/server.go:2514 +0x144
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x10474aef0?, 0x140023868c0?}, 0x140023868c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:47 +0x28
net/http.serverHandler.ServeHTTP({0x104735b58?}, {0x10474aef0?, 0x140023868c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x1401737dc20, {0x10475d550, 0x1400210a780})
	/usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 177
	/usr/local/go/src/net/http/server.go:3086 +0x4cc
2024/02/28 09:25:19 http: panic serving 127.0.0.1:56618: datastore: key not found
goroutine 21649 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1041cda60?, 0x1064ee180?})
	/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x14001711aa0, {0x1400aa5a1b0, 0x20, 0x1008d1eac?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/state/txindex/kv/kv.go:55 +0x1e4
github.com/rollkit/rollkit/node.(*FullClient).Tx(0x140013c6378, {0x10475d588, 0x1400dbcf450}, {0x1400aa5a1b0, 0x20, 0x21}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full_client.go:546 +0x60
github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x140012ac6c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/service.go:200 +0x5c
reflect.Value.call({0x1041725e0?, 0x1400139d170?, 0x140085838b8?}, {0x102e0d2e0, 0x4}, {0x14008583a08, 0x2, 0x45?})
	/usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1041725e0?, 0x1400139d170?, 0x1400851f7a0?}, {0x14008583a08?, 0x9?, 0x103e6c778?})
	/usr/local/go/src/reflect/value.go:380 +0x94
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x14001707da0, {0x10474aef0, 0x140023869a0}, 0x14001752800, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:93 +0x32c
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x1400010fb28?, {0x10474aef0?, 0x140023869a0?}, 0x100ba0dd0?)
	/usr/local/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x1400010fb58?, {0x10474aef0, 0x140023869a0}, 0x14001752800)
	/usr/local/go/src/net/http/server.go:2514 +0x144
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x10474aef0?, 0x140023869a0?}, 0x140023869a0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:47 +0x28
net/http.serverHandler.ServeHTTP({0x104735b58?}, {0x10474aef0?, 0x140023869a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x1401737de60, {0x10475d550, 0x1400210a780})
	/usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 177
	/usr/local/go/src/net/http/server.go:3086 +0x4cc
2024/02/28 09:25:20 http: panic serving 127.0.0.1:56620: datastore: key not found
goroutine 21731 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1041cda60?, 0x1064ee180?})
	/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/rollkit/rollkit/state/txindex/kv.(*TxIndex).Get(0x14001711aa0, {0x1400aa5a1e0, 0x20, 0x1008d1eac?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/state/txindex/kv/kv.go:55 +0x1e4
github.com/rollkit/rollkit/node.(*FullClient).Tx(0x140013c6378, {0x10475d588, 0x1400dbcf540}, {0x1400aa5a1e0, 0x20, 0x21}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full_client.go:546 +0x60
github.com/rollkit/rollkit/rpc/json.(*service).Tx(0x2?, 0x0?, 0x140012ac6c0?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/service.go:200 +0x5c
reflect.Value.call({0x1041725e0?, 0x1400139d170?, 0x140085838b8?}, {0x102e0d2e0, 0x4}, {0x14008583a08, 0x2, 0x45?})
	/usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1041725e0?, 0x1400139d170?, 0x1400851f820?}, {0x14008583a08?, 0x9?, 0x103e6c778?})
	/usr/local/go/src/reflect/value.go:380 +0x94
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPCforWS(0x14001707da0, {0x10474aef0, 0x14002386a80}, 0x14001752900, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:93 +0x32c
github.com/rollkit/rollkit/rpc/json.(*handler).serveJSONRPC(...)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:52
net/http.HandlerFunc.ServeHTTP(0x1400010fb28?, {0x10474aef0?, 0x14002386a80?}, 0x100ba0dd0?)
	/usr/local/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x1400010fb58?, {0x10474aef0, 0x14002386a80}, 0x14001752900)
	/usr/local/go/src/net/http/server.go:2514 +0x144
github.com/rollkit/rollkit/rpc/json.(*handler).ServeHTTP(0x10?, {0x10474aef0?, 0x14002386a80?}, 0x14002386a80?)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/rpc/json/handler.go:47 +0x28
net/http.serverHandler.ServeHTTP({0x104735b58?}, {0x10474aef0?, 0x14002386a80?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x14001504120, {0x10475d550, 0x1400210a780})
	/usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 177
	/usr/local/go/src/net/http/server.go:3086 +0x4cc
```

Steps to reproduce:
* Follow ibc docs in rollkit
* Run local-celestia-devnet
* Run GM rollup
* Run local osmosis testnet node
* Proceed to creating channels using ibc relayer
* Fire create channel command `rly transact link osmo-gm` and observe the panics in GM rollup logs.

**Comment by vuong177** [comment]
@gupadhyaya relayer will call `rpc.Tx` after broadcasting tx and it lead to
this panic.  I think this panics is similar with https://github.com/rollkit/rollkit/issues/1518
