### ISSUE TITLE
`TestTxGossipingAndAggregation` is not handling initialization errors properly

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1685]
As seen in: https://github.com/rollkit/rollkit/actions/runs/9257141294/job/25464645040?pr=1684#step:4:3702

```
    full_node_integration_test.go:743: 
        	Error Trace:	/home/runner/work/rollkit/rollkit/node/full_node_integration_test.go:743
        	            				/home/runner/work/rollkit/rollkit/node/full_node_integration_test.go:98
        	Error:      	Received unexpected error:
        	            	expected height > 2, got 0
        	Test:       	TestTxGossipingAndAggregation
panic: write /tmp/TestTxGossipingAndAggregationnode3.log1177626906: file already closed

goroutine 6413 [running]:
github.com/rollkit/rollkit/test/log.(*FileLogger).Debug(0xc01321b020, {0x2519c79, 0x20}, {0xc086df4380, 0x2, 0x8d226?})
	/home/runner/work/rollkit/rollkit/test/log/loggers.go:62 +0x3b6
github.com/rollkit/rollkit/block.(*Manager).processNextDABlock(0xc012f32400, {0x2a4ace8, 0xc012ef8be0})
	/home/runner/work/rollkit/rollkit/block/manager.go:670 +0x19f
github.com/rollkit/rollkit/block.(*Manager).RetrieveLoop(0xc012f32400, {0x2a4ace8, 0xc012ef8be0})
	/home/runner/work/rollkit/rollkit/block/manager.go:644 +0x20b
github.com/rollkit/rollkit/node.(*FullNode).OnStart.func5()
	/home/runner/work/rollkit/rollkit/node/full.go:395 +0x89
github.com/rollkit/rollkit/types.(*ThreadManager).Go.func1()
	/home/runner/work/rollkit/rollkit/types/threadmanager.go:26 +0x87
created by github.com/rollkit/rollkit/types.(*ThreadManager).Go in goroutine 5304
	/home/runner/work/rollkit/rollkit/types/threadmanager.go:24 +0xe5
FAIL	github.com/rollkit/rollkit/node	51.924s
```

There is some issue in `TestTxGossipingAndAggregation`.

**Comment by Manav-Aggarwal** [comment]
Related: https://github.com/rollkit/rollkit/pull/1434
