### ISSUE TITLE
Panic in `publishSignedHeader`

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#562]
Reported on Discord by `@aaraN`:
```
7:04PM INF successfully submitted rollmint block to DA layer daHeight=260299 module=BlockManager rollmintHeight=2
7:04PM INF commit synced commit=436F6D6D697449447B5B31373420313637203233332031372032353420313937203230342031363120373220313431203235342031393920313838203138392031303920313320343520313435203231372032333720313537203232322034312036332031303120393720313436203737203232332031373220313334203232355D3A327D
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c3d6e2]

goroutine 202 [running]:
github.com/celestiaorg/rollmint/block.(*Manager).publishSignedHeader(...)
    /home/aaransol/go/pkg/mod/github.com/celestiaorg/rollmint@v0.4.0/block/manager.go:526
github.com/celestiaorg/rollmint/block.(*Manager).publishBlock(0xc0015af8c0, {0x39cb280, 0xc00005a0f0})
    /home/aaransol/go/pkg/mod/github.com/celestiaorg/rollmint@v0.4.0/block/manager.go:487 +0x9a2
github.com/celestiaorg/rollmint/block.(*Manager).AggregationLoop(0xc0015af8c0, {0x39cb280, 0xc00005a0f0})
    /home/aaransol/go/pkg/mod/github.com/celestiaorg/rollmint@v0.4.0/block/manager.go:176 +0x105
created by github.com/celestiaorg/rollmint/node.(*Node).OnStart
    /home/aaransol/go/pkg/mod/github.com/celestiaorg/rollmint@v0.4.0/node/node.go:224 +0x245
exit status 2
```

**Comment by Manav-Aggarwal** [comment]
Closed since Rollkit uses `HeaderSync` for gossiping headers now.
