### ISSUE TITLE
Rollups are panicking if another rollup is writing to the same namespace

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#883]
Rullups are panicking if another rollup is writing to the same namespace.

<details>
<summary>Log of rollup 1</summary>

```log
docker compose -f docker/multi.docker-compose.yaml up gm
[+] Running 1/0
 ✔ Container docker-celestia-1  Running0.0s
Attaching to docker-gm-1
docker-gm-1  | + echo 'NAMESPACE_ID: 450ed35db52240c3'
docker-gm-1  | NAMESPACE_ID: 450ed35db52240c3
docker-gm-1  | + curl --silent http://celestia:26657/block
docker-gm-1  | + jq -r .result.block.header.height
docker-gm-1  | + DA_BLOCK_HEIGHT=1
docker-gm-1  | + echo 'DA_BLOCK_HEIGHT: 1'
docker-gm-1  | + '[' -z 1 ]
docker-gm-1  | + exec gmd start --rollkit.aggregator true --rollkit.da_layer celestia '--rollkit.da_config={"base_url":"http://celestia:26659","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id 450ed35db52240c3 --rollkit.da_start_height 1
docker-gm-1  | DA_BLOCK_HEIGHT: 1
docker-gm-1  | 9:44AM INF starting node with Rollkit in-process
docker-gm-1  | 9:44AM INF service start impl=EventBus module=events msg={}
docker-gm-1  | 9:44AM INF service start impl=PubSub module=pubsub msg={}
docker-gm-1  | 9:44AM INF service start impl=IndexerService module=txindex msg={}
docker-gm-1  | 9:44AM INF WARNING: using default DA block time DABlockTime=30000 module=BlockManager
docker-gm-1  | 9:44AM INF initializing blockchain state from genesis.json
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=1/12 module=x/crisis name=group/Group-TotalWeight
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=2/12 module=x/crisis name=staking/module-accounts
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=3/12 module=x/crisis name=staking/nonnegative-power
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=4/12 module=x/crisis name=staking/positive-delegation
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=5/12 module=x/crisis name=staking/delegator-shares
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=6/12 module=x/crisis name=bank/nonnegative-outstanding
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=7/12 module=x/crisis name=bank/total-supply
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=8/12 module=x/crisis name=gov/module-account
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=9/12 module=x/crisis name=distribution/nonnegative-outstanding
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=10/12 module=x/crisis name=distribution/can-withdraw
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=11/12 module=x/crisis name=distribution/reference-count
docker-gm-1  | 9:44AM INF asserting crisis invariants inv=12/12 module=x/crisis name=distribution/module-account
docker-gm-1  | 9:44AM INF asserted all invariants duration=1.020903 height=0 module=x/crisis
docker-gm-1  | 9:44AM INF created new capability module=ibc name=ports/transfer
docker-gm-1  | 9:44AM INF port binded module=x/ibc/port port=transfer
docker-gm-1  | 9:44AM INF claimed capability capability=1 module=transfer name=ports/transfer
docker-gm-1  | 9:44AM INF created new capability module=ibc name=ports/icahost
docker-gm-1  | 9:44AM INF port binded module=x/ibc/port port=icahost
docker-gm-1  | 9:44AM INF claimed capability capability=2 module=icahost name=ports/icahost
docker-gm-1  | 9:44AM INF service start impl=RPC msg={}
docker-gm-1  | 9:44AM INF service start impl=Node msg={}
docker-gm-1  | 9:44AM INF starting P2P client
docker-gm-1  | 9:44AM INF serving HTTP listen address={"IP":"127.0.0.1","Port":26657,"Zone":""}
docker-gm-1  | 9:44AM INF listening on address=/ip4/192.167.13.3/tcp/26656/p2p/12D3KooWD8c77EZ7pC8Saz2eeY6AyUL53vqynUMvNFfFYKqgRAvN module=p2p
docker-gm-1  | 9:44AM INF listening on address=/ip4/127.0.0.1/tcp/26656/p2p/12D3KooWD8c77EZ7pC8Saz2eeY6AyUL53vqynUMvNFfFYKqgRAvN module=p2p
docker-gm-1  | 9:44AM INF no seed nodes - only listening for connections module=p2p
docker-gm-1  | 9:44AM INF starting Celestia Data Availability Layer Client baseURL=http://celestia:26659 module=da_client
docker-gm-1  | 9:44AM INF working in aggregator mode block time=30000
docker-gm-1  | 9:44AM INF Creating and publishing block height=1 module=BlockManager
docker-gm-1  | 9:44AM INF minted coins from module account amount=411945206851145457stake from=mint module=x/bank
docker-gm-1  | 9:44AM INF submitting block to DA layer height=1 module=BlockManager
docker-gm-1  | 9:44AM INF successfully submitted Rollkit block to DA layer daHeight=2 module=BlockManager rollkitHeight=1
docker-gm-1  | 9:44AM INF commit synced commit=436F6D6D697449447B5B313038203134352031343620383220313135203135332032353420323130203139362031353120333720323034203133382031353120323334203232342035382035362031393620323436203234352034203938203138392031323120313232203732203133342031353020313231203430203138335D3A317D
docker-gm-1  | 9:44AM INF indexed block height=1 module=txindex
docker-gm-1  | 9:45AM INF Creating and publishing block height=2 module=BlockManager
docker-gm-1  | 9:45AM INF minted coins from module account amount=411945280604858579stake from=mint module=x/bank
docker-gm-1  | 9:45AM INF submitting block to DA layer height=2 module=BlockManager
docker-gm-1  | 9:45AM INF successfully submitted Rollkit block to DA layer daHeight=5 module=BlockManager rollkitHeight=2
docker-gm-1  | 9:45AM INF commit synced commit=436F6D6D697449447B5B313338203230322032313320383020373320383720323436203137322032333520333220313536203838203134342036342036203136362031353620313034203630203132203133392038342032313820313536203133332032343120343120393020393420313237203235352031345D3A327D
docker-gm-1  | 9:45AM INF indexed block height=2 module=txindex
docker-gm-1  | 9:45AM INF Creating and publishing block height=3 module=BlockManager
docker-gm-1  | 9:45AM INF minted coins from module account amount=411945354358575908stake from=mint module=x/bank
docker-gm-1  | 9:45AM INF submitting block to DA layer height=3 module=BlockManager
docker-gm-1  | 9:45AM INF successfully submitted Rollkit block to DA layer daHeight=8 module=BlockManager rollkitHeight=3
docker-gm-1  | 9:45AM INF commit synced commit=436F6D6D697449447B5B3230322038382034342031323120323030203630203332203638203530203730203337203134372031373420313132203134392031343020313838203536203137362031333320323138203138392031323620313632203936203231332031323620323332203136362031343520313736203133375D3A337D
docker-gm-1  | 9:45AM INF indexed block height=3 module=txindex
docker-gm-1  | 9:46AM INF Creating and publishing block height=4 module=BlockManager
docker-gm-1  | 9:46AM INF minted coins from module account amount=411945428112297445stake from=mint module=x/bank
docker-gm-1  | 9:46AM INF submitting block to DA layer height=4 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=1 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=2 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=3 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=4 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=5 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=6 module=BlockManager
docker-gm-1  | 9:46AM INF successfully submitted Rollkit block to DA layer daHeight=12 module=BlockManager rollkitHeight=4
docker-gm-1  | 9:46AM INF commit synced commit=436F6D6D697449447B5B323137203134352031323120313236203232302031393820363120313537203920393720313930203020313838203138352032303520313935203336203133382031322033362032333820313831203139372032303020323337203139352032203238203230352032303520323232203136345D3A347D
docker-gm-1  | 9:46AM INF indexed block height=4 module=txindex
docker-gm-1  | 9:46AM INF Creating and publishing block height=5 module=BlockManager
docker-gm-1  | 9:46AM INF minted coins from module account amount=411945501866023190stake from=mint module=x/bank
docker-gm-1  | 9:46AM INF submitting block to DA layer height=5 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=1 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=2 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=3 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=4 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=5 module=BlockManager
docker-gm-1  | 9:46AM ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=6 module=BlockManager
docker-gm-1  | 9:46AM INF Syncing block height=5 module=BlockManager
docker-gm-1  | 9:46AM INF minted coins from module account amount=411945575619753143stake from=mint module=x/bank
docker-gm-1  | 9:46AM INF commit synced commit=436F6D6D697449447B5B31343220313232203939203130362033392031323420313337203332203137302038312031323220313934203739203130203835203235203231362036372036382032313820323234203630203331203138312032313520313634203135342032353420323720313137203132302037395D3A357D
docker-gm-1  | 9:46AM INF indexed block height=5 module=txindex
docker-gm-1  | 9:46AM INF successfully submitted Rollkit block to DA layer daHeight=15 module=BlockManager rollkitHeight=5
docker-gm-1  | panic: runtime error: invalid memory address or nil pointer dereference
docker-gm-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x104874c]
docker-gm-1  |
docker-gm-1  | goroutine 266 [running]:
docker-gm-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0008b01c0)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/cosmos-sdk@v0.46.7-rollkit-v0.7.2-no-fraud-proofs/baseapp/abci.go:306 +0x4c
docker-gm-1  | github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc002c6f680)
docker-gm-1  |  /go/pkg/mod/github.com/celestiaorg/tendermint@v0.34.22-0.20221202214355-3605c597500d/abci/client/local_client.go:297 +0xb6
docker-gm-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).commit(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc0019f72ea, 0x2}, 0x1, ...}, ...)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:255 +0x122
docker-gm-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).Commit(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc0019f72ea, 0x2}, 0x1, ...}, ...)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:176 +0x88
docker-gm-1  | github.com/rollkit/rollkit/block.(*Manager).publishBlock(0xc000742000, {0x3844b20, 0xc00156df40})
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:537 +0x8b8
docker-gm-1  | github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0xc000742000, {0x3844b20, 0xc00156df40}, 0x0)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:211 +0x265
docker-gm-1  | created by github.com/rollkit/rollkit/node.(*FullNode).OnStart
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/node/full.go:267 +0x2bd
docker-gm-1 exited with code 0
```

</details>

<details>
<summary>Log of rollup 2</summary>

```log
 docker compose -f docker/multi.docker-compose.yaml up gm2
[+] Running 2/0
 ✔ Container docker-celestia-1  Running    0.0s
 ✔ Container docker-gm2-1       Created    0.0s
Attaching to docker-gm2-1
docker-gm2-1  | + echo 'NAMESPACE_ID: 450ed35db52240c3'
docker-gm2-1  | NAMESPACE_ID: 450ed35db52240c3
docker-gm2-1  | + jq+  -r .result.block.header.height
docker-gm2-1  | curl --silent http://celestia:26657/block
docker-gm2-1  | DA_BLOCK_HEIGHT: 5
docker-gm2-1  | + DA_BLOCK_HEIGHT=5
docker-gm2-1  | + echo 'DA_BLOCK_HEIGHT: 5'
docker-gm2-1  | + '[' -z 5 ]
docker-gm2-1  | + exec gmd start --rollkit.aggregator true --rollkit.da_layer celestia '--rollkit.da_config={"base_url":"http://celestia:26659","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id 450ed35db52240c3 --rollkit.da_start_height 5 --home /home/rollkit/.gm2
docker-gm2-1  | 9:45AM INF starting node with Rollkit in-process
docker-gm2-1  | 9:45AM INF service start impl=EventBus module=events msg={}
docker-gm2-1  | 9:45AM INF service start impl=PubSub module=pubsub msg={}
docker-gm2-1  | 9:45AM INF service start impl=IndexerService module=txindex msg={}
docker-gm2-1  | 9:45AM INF WARNING: using default DA block time DABlockTime=30000 module=BlockManager
docker-gm2-1  | 9:45AM INF initializing blockchain state from genesis.json
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=1/12 module=x/crisis name=staking/module-accounts
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=2/12 module=x/crisis name=staking/nonnegative-power
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=3/12 module=x/crisis name=staking/positive-delegation
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=4/12 module=x/crisis name=staking/delegator-shares
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=5/12 module=x/crisis name=bank/nonnegative-outstanding
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=6/12 module=x/crisis name=bank/total-supply
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=7/12 module=x/crisis name=group/Group-TotalWeight
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=8/12 module=x/crisis name=gov/module-account
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=9/12 module=x/crisis name=distribution/nonnegative-outstanding
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=10/12 module=x/crisis name=distribution/can-withdraw
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=11/12 module=x/crisis name=distribution/reference-count
docker-gm2-1  | 9:45AM INF asserting crisis invariants inv=12/12 module=x/crisis name=distribution/module-account
docker-gm2-1  | 9:45AM INF asserted all invariants duration=1.135826 height=0 module=x/crisis
docker-gm2-1  | 9:45AM INF created new capability module=ibc name=ports/transfer
docker-gm2-1  | 9:45AM INF port binded module=x/ibc/port port=transfer
docker-gm2-1  | 9:45AM INF claimed capability capability=1 module=transfer name=ports/transfer
docker-gm2-1  | 9:45AM INF created new capability module=ibc name=ports/icahost
docker-gm2-1  | 9:45AM INF port binded module=x/ibc/port port=icahost
docker-gm2-1  | 9:45AM INF claimed capability capability=2 module=icahost name=ports/icahost
docker-gm2-1  | 9:45AM INF service start impl=RPC msg={}
docker-gm2-1  | 9:45AM INF service start impl=Node msg={}
docker-gm2-1  | 9:45AM INF starting P2P client
docker-gm2-1  | 9:45AM INF serving HTTP listen address={"IP":"127.0.0.1","Port":26657,"Zone":""}
docker-gm2-1  | 9:45AM INF listening on address=/ip4/192.167.13.4/tcp/26656/p2p/12D3KooWEJp4CGg4FnScvuTPrZ3SPAVXU3M6AJecrZCiTU6vc2iX module=p2p
docker-gm2-1  | 9:45AM INF listening on address=/ip4/127.0.0.1/tcp/26656/p2p/12D3KooWEJp4CGg4FnScvuTPrZ3SPAVXU3M6AJecrZCiTU6vc2iX module=p2p
docker-gm2-1  | 9:45AM INF no seed nodes - only listening for connections module=p2p
docker-gm2-1  | 9:45AM INF starting Celestia Data Availability Layer Client baseURL=http://celestia:26659 module=da_client
docker-gm2-1  | 9:45AM INF working in aggregator mode block time=30000
docker-gm2-1  | 9:45AM INF Creating and publishing block height=1 module=BlockManager
docker-gm2-1  | 9:45AM INF minted coins from module account amount=411945206851145457stake from=mint module=x/bank
docker-gm2-1  | 9:45AM INF submitting block to DA layer height=1 module=BlockManager
docker-gm2-1  | 9:45AM INF successfully submitted Rollkit block to DA layer daHeight=6 module=BlockManager rollkitHeight=1
docker-gm2-1  | 9:45AM INF commit synced commit=436F6D6D697449447B5B31382032323420363120313537203136312039322031392032343420313237203131332036382031363220363520323238203130302034203131382032323820313339203136312033203739203730203338203230382031333220323239203137342031373420313230203138382038325D3A317D
docker-gm2-1  | 9:45AM INF indexed block height=1 module=txindex
docker-gm2-1  | 9:45AM INF Creating and publishing block height=2 module=BlockManager
docker-gm2-1  | 9:45AM INF minted coins from module account amount=411945280604858579stake from=mint module=x/bank
docker-gm2-1  | 9:45AM INF Syncing block height=2 module=BlockManager
docker-gm2-1  | 9:45AM INF submitting block to DA layer height=2 module=BlockManager
docker-gm2-1  | 9:45AM INF minted coins from module account amount=411945354358575908stake from=mint module=x/bank
docker-gm2-1  | 9:45AM INF commit synced commit=436F6D6D697449447B5B313037203133342031383220313530203136362031393220333620323334203135382032343820313733203132392031363820323420313738203435203130342032313020323430203138302035332031353520313139203330203232392032303520313131203232332031313820373820313431203131375D3A327D
docker-gm2-1  | 9:45AM INF Syncing block height=3 module=BlockManager
docker-gm2-1  | 9:45AM INF indexed block height=2 module=txindex
docker-gm2-1  | 9:45AM INF minted coins from module account amount=411945428112297445stake from=mint module=x/bank
docker-gm2-1  | 9:45AM INF commit synced commit=436F6D6D697449447B5B3133342036302031313320313020323230203139362032343920363420313020313033203734203232342031393720393620373920323338203235203138392031363220313139203134332031383820373720313438203131382032343320323434203130312032343220323038203132392033395D3A337D
docker-gm2-1  | 9:45AM INF indexed block height=3 module=txindex
docker-gm2-1  | 9:45AM INF successfully submitted Rollkit block to DA layer daHeight=9 module=BlockManager rollkitHeight=2
docker-gm2-1  | panic: runtime error: invalid memory address or nil pointer dereference
docker-gm2-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x104874c]
docker-gm2-1  |
docker-gm2-1  | goroutine 93 [running]:
docker-gm2-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0006b0380)
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/cosmos-sdk@v0.46.7-rollkit-v0.7.2-no-fraud-proofs/baseapp/abci.go:306 +0x4c
docker-gm2-1  | github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc001bffe00)
docker-gm2-1  |         /go/pkg/mod/github.com/celestiaorg/tendermint@v0.34.22-0.20221202214355-3605c597500d/abci/client/local_client.go:297 +0xb6
docker-gm2-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).commit(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc001fdd32a, 0x2}, 0x1, ...}, ...)
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:255 +0x122
docker-gm2-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).Commit(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc001fdd32a, 0x2}, 0x1, ...}, ...)
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:176 +0x88
docker-gm2-1  | github.com/rollkit/rollkit/block.(*Manager).publishBlock(0xc001f58b40, {0x3844b20, 0xc001114240})
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:537 +0x8b8
docker-gm2-1  | github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0xc001f58b40, {0x3844b20, 0xc001114240}, 0x0)
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:211 +0x265
docker-gm2-1  | created by github.com/rollkit/rollkit/node.(*FullNode).OnStart
docker-gm2-1  |         /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/node/full.go:267 +0x2bd
docker-gm2-1 exited with code 0
```

</details>

<details>
<summary>gensis setup</summary>

```shell
#!/bin/sh

set -x

# set variables for the chain
VALIDATOR_NAME=validator1
VALIDATOR_2_NAME=validator2
CHAIN_ID=gm
KEY_NAME=gm-key
KEY_2_NAME=gm-key-2
KEY2_NAME=gm2-key
CHAINFLAG="--chain-id ${CHAIN_ID}"
TOKEN_AMOUNT="10000000000000000000000000stake"
STAKING_AMOUNT="1000000000stake"

# initialize the validator with the chain ID you set
gmd init $VALIDATOR_NAME --chain-id $CHAIN_ID
gmd init $VALIDATOR_2_NAME --chain-id $CHAIN_ID --home $HOME/.gm2

# add keys for key 1 and key 2 to keyring-backend test
gmd keys add $KEY_NAME --keyring-backend test
gmd keys add $KEY_2_NAME --keyring-backend test
gmd keys add $KEY2_2_NAME --keyring-backend test --home $HOME/.gm2

# copy the keys so that they are available to both nodes
# cp $HOME/.gm2/keyring-test/* $HOME/.gm/keyring-test/
# cp $HOME/.gm/keyring-test/* $HOME/.gm2/keyring-test/

# copy all keys so that they are available to both nodes
cp $HOME/.gm2/config/priv_validator_key.json $HOME/.gm/config/priv_validator_key.json
cp $HOME/.gm/config/priv_validator_key.json $HOME/.gm2/config/priv_validator_key.json

# add these as genesis accounts
gmd add-genesis-account $KEY_NAME $TOKEN_AMOUNT --keyring-backend test
gmd add-genesis-account $KEY_2_NAME $TOKEN_AMOUNT --keyring-backend test

# All should have the same genesis.json
cp $HOME/.gm/config/genesis.json $HOME/.gm2/config/genesis.json

# set the staking amounts in the genesis transaction
gmd gentx $KEY_NAME $STAKING_AMOUNT --chain-id $CHAIN_ID --keyring-backend test --ip "192.167.13.3"
gmd gentx $KEY_2_NAME $STAKING_AMOUNT --chain-id $CHAIN_ID --keyring-backend test --home $HOME/.gm2 --ip "192.167.13.4"

cp $HOME/.gm2/config/gentx/*.json $HOME/.gm/config/gentx/

# collect genesis transactions
gmd collect-gentxs

cp $HOME/.gm/config/genesis.json $HOME/.gm2/config/genesis.json


export NAMESPACE_ID=$(echo $RANDOM | md5sum | head -c 16; echo)
```

</details>

<details>
<summary>entrypoint</summary>

```shell
#!/bin/sh

# print all commands before executing them
set -x

# create a random Namespace ID for your rollup to post blocks to
# NAMESPACE_ID=$(echo $RANDOM | md5sum | head -c 16; echo)
echo "NAMESPACE_ID: $NAMESPACE_ID"

# query the DA Layer start height, in this case we are querying
# our local devnet at port 26657, the RPC. The RPC endpoint is
# to allow users to interact with Celestia's nodes by querying
# the node's state and broadcasting transactions on the Celestia
# network. The default port is 26657.
DA_BLOCK_HEIGHT=$(curl --silent ${RPC%/}${RPC:+/}block | jq -r '.result.block.header.height')
# DA_BLOCK_HEIGHT=0
echo "DA_BLOCK_HEIGHT: $DA_BLOCK_HEIGHT"

if [ -z "$DA_BLOCK_HEIGHT" ]; then
    echo "DA_BLOCK_HEIGHT is empty; ensure that the DA Layer is running and accessible"
    exit 1
fi

exec gmd start --rollkit.aggregator true --rollkit.da_layer celestia --rollkit.da_config='{"base_url":"http://celestia:26659","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id $NAMESPACE_ID --rollkit.da_start_height $DA_BLOCK_HEIGHT $START_ARGS

```

</details>

If more information is needed, please let me know.

## Reproduce the error

Make sure to have docker and docker compose installed.

1. Clone [rollkit/gm](https://github.com/rollkit/gm)
2. Navigate to the `docker` directory
3. Create a new file in the `docker` directory named `883.docker-compose.yaml` with the following content:

<details>
<summary>883.docker-compose.yaml</summary>

This docker compose file allows you to start 2 gm rollup nodes running on top of `local-celestia-devnet` where a consensus validator and DA bridge get's started.
Both are configured to be an aggregator and to use the same namespace.

```yaml
version: "3"

services:
  celestia:
    image: ghcr.io/rollkit/local-celestia-devnet:v0.8.2
    restart: unless-stopped
    expose:
      - "26657"
      - "26659"
    # Rollup can't start until after DA starts.
    # This ensures it waits 5 seconds so the rollup can query it.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/block?height=1"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      localnet:
        ipv4_address: 192.167.13.2
  gm:
    build:
      context: .
    restart: unless-stopped
    expose:
      - "26656"
    ports:
      - "26657:26657"
    environment:
      - RPC=http://celestia:26657/
      - START_ARGS=--rollkit.aggregator
      - DA_BLOCK_HEIGHT=1
      - NAMESPACE_ID=1315168a27ece416
    depends_on:
      celestia:
        condition: service_healthy
    networks:
      localnet:
        ipv4_address: 192.167.13.3
  gm2:
    build:
      context: .
    restart: unless-stopped
    expose:
      - "26656"
    ports:
      - "36657:26657"
    environment:
      - RPC=http://celestia:26657/
      - START_ARGS=--rollkit.aggregator
      - DA_BLOCK_HEIGHT=1
      - NAMESPACE_ID=1315168a27ece416
    depends_on:
      celestia:
        condition: service_healthy
    networks:
      localnet:
        ipv4_address: 192.167.13.4


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.13.0/24
          gateway: 192.167.13.1
```

</details>

4. Start local-celestia-devnet in background with `docker compose -f 883.docker-compose.yaml up celestia -d`
5. Build the rollup `docker compose -f 883.docker-compose.yaml build --no-cache`
6. Start the first rollup node with `docker compose -f 883.docker-compose.yaml up gm`
7. Open a second chell
8. Rebuild the rollup `docker compose -f 883.docker-compose.yaml build --no-cache` in order to create new keys and a new `genesis.json`
9. Start the second rollup node with `docker compose -f 883.docker-compose.yaml up gm2`
10. Wait until nodes are crashing
11. To clean up, you can use `docker compose -f 883.docker-compose.yaml down`

**Comment by Manav-Aggarwal** [comment]
Check if `isUsingExpectedCentralizedSequencer` method in block manager gets rid of this issue.
