### ISSUE TITLE
Panic Error on Rollkit Node at 'random' block height

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#884]
When running a Rollkit node, I encountered a panic error at block height 4, where the error message states: "panic: invalid height: 4; expected: 5".

The error occurred after the node successfully synced and committed block heights 1-4 to the Celestia Data Availability Layer but failed to create and publish the next block at height 5 due to this error.

<details>
<summary>Logs</summary>

```log
docker-gm-1  | + cat /home/rollkit/NAMESPACE_ID
docker-gm-1  | + NAMESPACE_ID=c6e4e62a942a751e
docker-gm-1  | + curl --silent http://celestia:26657/block
docker-gm-1  | + jq -r .result.block.header.height
docker-gm-1  | + DA_BLOCK_HEIGHT=52
docker-gm-1  | + echo 'DA_BLOCK_HEIGHT: 52'
docker-gm-1  | + '[' -z 52 ]
docker-gm-1  | + exec gmd start --rollkit.da_layer celestia '--rollkit.da_config={"base_url":"http://celestia:26659","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id c6e4e62a942a751e --rollkit.da_start_height 52 --rollkit.aggregator
docker-gm-1  | DA_BLOCK_HEIGHT: 52
docker-gm-1  | 12:32PM INF starting node with Rollkit in-process
docker-gm-1  | 12:32PM INF service start impl=EventBus module=events msg={}
docker-gm-1  | 12:32PM INF service start impl=PubSub module=pubsub msg={}
docker-gm-1  | 12:32PM INF service start impl=IndexerService module=txindex msg={}
docker-gm-1  | 12:32PM INF WARNING: using default DA block time DABlockTime=30000 module=BlockManager
docker-gm-1  | 12:32PM INF initializing blockchain state from genesis.json
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=1/12 module=x/crisis name=distribution/nonnegative-outstanding
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=2/12 module=x/crisis name=distribution/can-withdraw
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=3/12 module=x/crisis name=distribution/reference-count
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=4/12 module=x/crisis name=distribution/module-account
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=5/12 module=x/crisis name=staking/module-accounts
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=6/12 module=x/crisis name=staking/nonnegative-power
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=7/12 module=x/crisis name=staking/positive-delegation
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=8/12 module=x/crisis name=staking/delegator-shares
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=9/12 module=x/crisis name=bank/nonnegative-outstanding
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=10/12 module=x/crisis name=bank/total-supply
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=11/12 module=x/crisis name=group/Group-TotalWeight
docker-gm-1  | 12:32PM INF asserting crisis invariants inv=12/12 module=x/crisis name=gov/module-account
docker-gm-1  | 12:32PM INF asserted all invariants duration=1.015106 height=0 module=x/crisis
docker-gm-1  | 12:32PM INF created new capability module=ibc name=ports/transfer
docker-gm-1  | 12:32PM INF port binded module=x/ibc/port port=transfer
docker-gm-1  | 12:32PM INF claimed capability capability=1 module=transfer name=ports/transfer
docker-gm-1  | 12:32PM INF created new capability module=ibc name=ports/icahost
docker-gm-1  | 12:32PM INF port binded module=x/ibc/port port=icahost
docker-gm-1  | 12:32PM INF claimed capability capability=2 module=icahost name=ports/icahost
docker-gm-1  | 12:32PM INF service start impl=RPC msg={}
docker-gm-1  | 12:32PM INF service start impl=Node msg={}
docker-gm-1  | 12:32PM INF starting P2P client
docker-gm-1  | 12:32PM INF serving HTTP listen address={"IP":"127.0.0.1","Port":26657,"Zone":""}
docker-gm-1  | 12:32PM INF listening on address=/ip4/192.167.13.3/tcp/26656/p2p/12D3KooWAHfvrahnHguH3uosazYkkVqwwivsfq4RykMHvAgSBiuP module=p2p
docker-gm-1  | 12:32PM INF listening on address=/ip4/127.0.0.1/tcp/26656/p2p/12D3KooWAHfvrahnHguH3uosazYkkVqwwivsfq4RykMHvAgSBiuP module=p2p
docker-gm-1  | 12:32PM INF no seed nodes - only listening for connections module=p2p
docker-gm-1  | 12:32PM INF starting Celestia Data Availability Layer Client baseURL=http://celestia:26659 module=da_client
docker-gm-1  | 12:32PM INF working in aggregator mode block time=30000
docker-gm-1  | 12:32PM INF Creating and publishing block height=1 module=BlockManager
docker-gm-1  | 12:32PM INF minted coins from module account amount=411945206851145457stake from=mint module=x/bank
docker-gm-1  | 12:32PM INF submitting block to DA layer height=1 module=BlockManager
docker-gm-1  | 12:32PM INF successfully submitted Rollkit block to DA layer daHeight=53 module=BlockManager rollkitHeight=1
docker-gm-1  | 12:32PM INF commit synced commit=436F6D6D697449447B5B3132372037362032312032343720323720313931203137203137302032323120323131203234362031363820393520313620313736203530203330203136332031303320353820363220323138203534203133302031383720363120323433203136342032333520333920313036203131315D3A317D
docker-gm-1  | 12:32PM INF indexed block height=1 module=txindex
docker-gm-1  | 12:32PM INF Creating and publishing block height=2 module=BlockManager
docker-gm-1  | 12:32PM INF minted coins from module account amount=411945280604858579stake from=mint module=x/bank
docker-gm-1  | 12:32PM INF submitting block to DA layer height=2 module=BlockManager
docker-gm-1  | 12:32PM INF successfully submitted Rollkit block to DA layer daHeight=56 module=BlockManager rollkitHeight=2
docker-gm-1  | 12:32PM INF commit synced commit=436F6D6D697449447B5B32302032353020313139203231382039342032333920313938203538203632203439203134312031353920393120323620313738203130352031313620343020383320333220323230203230332031343220313634203234342032313320313837203133312032333420313535203333203134355D3A327D
docker-gm-1  | 12:32PM INF indexed block height=2 module=txindex
docker-gm-1  | 12:33PM INF Creating and publishing block height=3 module=BlockManager
docker-gm-1  | 12:33PM INF minted coins from module account amount=411945354358575908stake from=mint module=x/bank
docker-gm-1  | 12:33PM INF submitting block to DA layer height=3 module=BlockManager
docker-gm-1  | 12:33PM INF successfully submitted Rollkit block to DA layer daHeight=59 module=BlockManager rollkitHeight=3
docker-gm-1  | 12:33PM INF commit synced commit=436F6D6D697449447B5B373920313720323337203133312032353020323237203137203935203733203136302032203433203138382031373020313420323430203930203233362031313420343920393620313237203231302035382037362031353420323138203136322036372033362033203233345D3A337D
docker-gm-1  | 12:33PM INF indexed block height=3 module=txindex
docker-gm-1  | 12:33PM INF Creating and publishing block height=4 module=BlockManager
docker-gm-1  | 12:33PM INF minted coins from module account amount=411945428112297445stake from=mint module=x/bank
docker-gm-1  | 12:33PM INF submitting block to DA layer height=4 module=BlockManager
docker-gm-1  | 12:33PM INF successfully submitted Rollkit block to DA layer daHeight=62 module=BlockManager rollkitHeight=4
docker-gm-1  | 12:33PM INF Syncing block height=4 module=BlockManager
docker-gm-1  | 12:33PM INF commit synced commit=436F6D6D697449447B5B323138203133302032303220313535203138312034322031343820313637203138362031383420323434203137332038332034322031323820313238203937203138362032303920353520323531203230302031303320333620313635203231372031323220383320373820313420313235203137395D3A347D
docker-gm-1  | 12:33PM INF indexed block height=4 module=txindex
docker-gm-1  | panic: invalid height: 4; expected: 5
docker-gm-1  | 
docker-gm-1  | goroutine 156 [running]:
docker-gm-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00a0f4440, 0x20, 0x20}, {{0xb, 0x0}, {0xc002240c0a, 0x2}, 0x4, {0x0, ...}, ...}, ...})
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/cosmos-sdk@v0.46.7-rollkit-v0.7.2-no-fraud-proofs/baseapp/abci.go:143 +0xaa5
docker-gm-1  | github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00a0f4440, 0x20, 0x20}, {{0xb, 0x0}, {0xc002240c0a, 0x2}, 0x4, {0x0, ...}, ...}, ...})
docker-gm-1  |  /go/pkg/mod/github.com/celestiaorg/tendermint@v0.34.22-0.20221202214355-3605c597500d/abci/client/local_client.go:313 +0x118
docker-gm-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).execute(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc002240c0a, 0x2}, 0x1, ...}, ...)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:371 +0x575
docker-gm-1  | github.com/rollkit/rollkit/state.(*BlockExecutor).ApplyBlock(_, {_, _}, {{{0xb, 0x0}, {0x2835fa2, 0x7}}, {0xc002240c0a, 0x2}, 0x1, ...}, ...)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/state/executor.go:144 +0xf8
docker-gm-1  | github.com/rollkit/rollkit/block.(*Manager).trySyncNextBlock(0xc001bc4480, {0x3844b20, 0xc008b161c0}, 0x3e)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:324 +0x1f0
docker-gm-1  | github.com/rollkit/rollkit/block.(*Manager).SyncLoop(0xc001bc4480, {0x3844b20, 0xc008b161c0}, 0xc00150b0e0)
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/block/manager.go:268 +0x6fd
docker-gm-1  | created by github.com/rollkit/rollkit/node.(*FullNode).OnStart
docker-gm-1  |  /go/pkg/mod/github.com/rollkit/rollkit@v0.7.2/node/full.go:271 +0x49c
docker-gm-1 exited with code 0
```
</details>

I reran it multiple times and got the error on different heights and sometimes I stopped the test at a 'large' height.

<details>
<summary>Failing tests</summary>

NAMESPACE_ID=c6e4e62a942a751e
DA_BLOCK_HEIGHT=52
panic: invalid height: 4; expected: 5

NAMESPACE_ID=c3b6c8cfc0a9eb09
DA_BLOCK_HEIGHT: 181
panic: invalid height: 6; expected: 7
</details>

<details>
<summary>Stopped tests</summary>

NAMESPACE_ID=511623874a3f8a7a
DA_BLOCK_HEIGHT=74
stopped the test at height 36

NAMESPACE_ID=7e54f88ff5b3a684
DA_BLOCK_HEIGHT: 219
stopped the test at height 40

NAMESPACE_ID=59885ebc737617ad
DA_BLOCK_HEIGHT: 351
stopped the test at height 33
</details>

Additionally, I wonder why the program exits with a code 0 in a panic.

**Comment by nashqueue** [comment]
Can you post the steps to reproduce this bug?

**Comment by gupadhyaya** [comment]
the issue #816 was non-deterministic. what was happening is that the sequencer is publishing block at the same time trying to sync. he is pushing the block to DA and then updating the local store height much later. in between sync is fetching the old height and trying to sync the block again, hence the issue. 
the fix was to update the store height as soon as DA submit is successful as seen in https://github.com/rollkit/rollkit/blob/main/block/manager.go#L570

since this error is happening again, even when we have the submitToDA and updating the store height right after each other, we need to investigate this further. but, let's first confirm this is reproducible consistently.
