### ISSUE TITLE
Wait Group goes negative in TestFutureGenesisTime

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#936]
Command to reproduce:
`go test --run FutureGenesisTime --race --count=2`

Result:
`````
panic: sync: negative WaitGroup counter

goroutine 171 [running]:
sync.(*WaitGroup).Add(0xc00099c9e0, 0xffffffffffffffff)
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/sync/waitgroup.go:83 +0x1a8
sync.(*WaitGroup).Done(...)
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/sync/waitgroup.go:108
github.com/rollkit/rollkit/node.TestFutureGenesisTime.func1({0xc0006a43b8?, 0xc000247600?, 0xa?})
        /Users/manav/Documents/Celestia/rollkit/node/full_client_test.go:1155 +0x98
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0006a4370, {0x10224aa23, 0xa}, {0xc006ac0ee0, 0x1, 0x1})
        /Users/manav/go/pkg/mod/github.com/stretchr/testify@v1.8.2/mock/mock.go:544 +0xcd4
github.com/stretchr/testify/mock.(*Mock).Called(0x101e96c00?, {0xc006ac0ee0, 0x1, 0x1})
        /Users/manav/go/pkg/mod/github.com/stretchr/testify@v1.8.2/mock/mock.go:456 +0x144
github.com/rollkit/rollkit/mocks.(*Application).BeginBlock(_, {{0xc0006c4200, 0x20, 0x20}, {{0xb, 0x0}, {0x1015353c6, 0x4}, 0x2, {0x0, ...}, ...}, ...})
        /Users/manav/Documents/Celestia/rollkit/mocks/Application.go:31 +0xd0
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0006c4200, 0x20, 0x20}, {{0xb, 0x0}, {0x1015353c6, 0x4}, 0x2, {0x0, ...}, ...}, ...})
        /Users/manav/go/pkg/mod/github.com/celestiaorg/tendermint@v0.34.22-0.20221202214355-3605c597500d/abci/client/local_client.go:313 +0x10c
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0006c4200, 0x20, 0x20}, {{0xb, 0x0}, {0x1015353c6, 0x4}, 0x2, {0x0, ...}, ...}, ...})
        /Users/manav/go/pkg/mod/github.com/celestiaorg/tendermint@v0.34.22-0.20221202214355-3605c597500d/proxy/app_conn.go:84 +0x84
github.com/rollkit/rollkit/state.(*BlockExecutor).execute(_, {_, _}, {{{0xb, 0x0}, {0x10155c9c0, 0x7}}, {0x1015353c6, 0x4}, 0x1, ...}, ...)
        /Users/manav/Documents/Celestia/rollkit/state/executor.go:388 +0x564
github.com/rollkit/rollkit/state.(*BlockExecutor).ApplyBlock(_, {_, _}, {{{0xb, 0x0}, {0x10155c9c0, 0x7}}, {0x1015353c6, 0x4}, 0x1, ...}, ...)
        /Users/manav/Documents/Celestia/rollkit/state/executor.go:147 +0xa8
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0xc000308b40, {0x101fb8238, 0xc0005ca740})
        /Users/manav/Documents/Celestia/rollkit/block/manager.go:545 +0x8b4
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0xc000308b40, {0x101fb8238, 0xc0005ca740}, 0x0)
        /Users/manav/Documents/Celestia/rollkit/block/manager.go:216 +0x300
created by github.com/rollkit/rollkit/node.(*FullNode).OnStart
        /Users/manav/Documents/Celestia/rollkit/node/full.go:298 +0x85c
exit status 2
FAIL    github.com/rollkit/rollkit/node 1.861s
```

**Comment by tac0turtle** [comment]
test seems to be passing now
